general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl eval 'hl.dispatch(hl.dsp.dpms({action = "on"}))'
    ignore_dbus_inhibit = true
    on_unlock_cmd = pkill hypridle
}

listener {
    timeout = 2
    on-timeout = loginctl lock-session
}

listener {
    timeout = 5
    on-timeout = hyprctl eval 'hl.dispatch(hl.dsp.dpms({action = "off"}))'
    on-resume = hyprctl eval 'hl.dispatch(hl.dsp.dpms({action = "on"}))'
}
